### ISSUE TITLE
Error: Invalid Character

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws2tf#34] opened 2023-02-28 12:34 UTC
Encountered this error with error log piped "./aws2tf.sh -v yes  | tee output.log"

> Error: Invalid character
> 
>   on aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf line 22, in resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget":
>   22: input_template = "={ \"title\": \"Auto Scaling EC2 instance launch failed\", \"description\": \"CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.\", \"source\": \"EC2 Auto Scaling\", \"category\": \"Availability\", \"severity\":\"2\", \"resources\": <resources>, \"operationalData\": { \"/aws/dedup\": {\"type\": \"SearchableString\", \"value\": \"{\\"dedupString\\":\\"SSMOpsItems-Autoscaling-instance-launch-failure\\"}\"}, \"/aws/automations\": { \"value\": \"[ { \\"automationType\\": \\"AWS:SSM:Automation\\", \\"automationId\\": \\"AWS-ASGEnterStandby\\" }, { \\"automationType\\": \\"AWS:SSM:Automation\\", \\"automationId\\": \\"AWS-ASGExitStandby\\" } ]\" }, \"autoscaling-group-name\": {\"value\": <autoscaling-group-name>}, \"status-message\": {\"value\": <status-message>}, \"start-time\": {\"value\": <start-time>}, \"end-time\": {\"value\": <end-time>}, \"cause\": {\"value\": <cause>}} }"
> 
> This character is not used within the language.

**Comment by ahkai86** [comment] 2023-03-01 10:24
performed -> terraform state show aws_cloudwatch_event_target.default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget

> terraform state show aws_cloudwatch_event_target.default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget
> # aws_cloudwatch_event_target.default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget:
> resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget" {
>     arn            = "arn:aws:ssm:ap-southeast-1:xxxxxxxxxxxx:opsitem"
>     event_bus_name = "default"
>     id             = "SSMOpsItems-Autoscaling-instance-launch-failure-SSMOpsItems-Autoscaling-instance-launch-failureTarget"
>     role_arn       = "arn:aws:iam::xxxxxxxxxxxx:role/service-role/OpsItem-CWE-Role"
>     rule           = "SSMOpsItems-Autoscaling-instance-launch-failure"
>     target_id      = "SSMOpsItems-Autoscaling-instance-launch-failureTarget"
> 
>     input_transformer {
>         input_paths    = {
>             "autoscaling-group-name" = "$.detail.AutoScalingGroupName"
>             "cause"                  = "$.detail.Cause"
>             "end-time"               = "$.detail.EndTime"
>             "resources"              = "$.resources"
>             "start-time"             = "$.detail.StartTime"
>             "status-message"         = "$.detail.StatusMessage"
>         }
>         input_template = "{ \"title\": \"Auto Scaling EC2 instance launch failed\", \"description\": \"CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.\", \"source\": \"EC2 Auto Scaling\", \"category\": \"Availability\", \"severity\":\"2\", \"resources\": <resources>, \"operationalData\": { \"/aws/dedup\": {\"type\": \"SearchableString\",                \"value\": \"{\\\"dedupString\\\":\\\"SSMOpsItems-Autoscaling-instance-launch-failure\\\"}\"}, \"/aws/automations\": { \"value\": \"[ { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGEnterStandby\\\" }, { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGExitStandby\\\" } ]\" }, \"autoscaling-group-name\": {\"value\": <autoscaling-group-name>}, \"status-message\": {\"value\": <status-message>}, \"start-time\": {\"value\": <start-time>}, \"end-time\": {\"value\": <end-time>}, \"cause\": {\"value\": <cause>}} }"
>     }
> }

**Comment by awsandy** [comment] 2023-03-01 20:21
Thanks that was super helpful.
Committed changes that hopefully will fix this.

**Comment by ahkai86** [comment] 2023-03-02 13:17
terraform error on: aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf

<img width="1354" alt="Screenshot 2023-03-02 at 9 16 08 PM" src="https://user-images.githubusercontent.com/38812404/222439156-94afbd9f-2f45-4a55-8f89-a7a70a0f474a.png">

**Comment by awsandy** [comment] 2023-03-02 13:23
Can you post that full line that is showing the error form the .tf file

input_template= ...................

**Comment by ahkai86** [comment] 2023-03-02 13:30
input_template = jsonencode({ "title": "Auto Scaling EC2 instance launch failed", "description": "CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.", "source": "EC2 Auto Scaling", "category": "Availability", "severity":"2", "resources": <resources>, "operationalData": { "/aws/dedup": {"type": "SearchableString", "value": "{\"dedupString\":\"SSMOpsItems-Autoscaling-instance-launch-failure\"}"}, "/aws/automations": { "value": "[ { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGEnterStandby\" }, { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGExitStandby\" } ]" }, "autoscaling-group-name": {"value": <autoscaling-group-name>}, "status-message": {"value": <status-message>}, "start-time": {"value": <start-time>}, "end-time": {"value": <end-time>}, "cause": {"value": <cause>}} })

**Comment by awsandy** [comment] 2023-03-02 19:03
That screen grab - it that just a vscode extension objecting to the code ?
Does it pass terraform validate (it does here)

**Comment by awsandy** [comment] 2023-03-03 18:43
This tool doesn't cover VSCode plug-in's - I think the plug-in is also wrong to flag it , the code inside the jsonencode is valid json , and is ok for the terraform validate

**Comment by ahkai86** [comment] 2023-03-05 08:16
the only error i encountered after all the fixes, not if it will affect others as well for cloudwatch:

Error: Invalid expression

  on aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf line 22, in resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget":
  22: input_template = jsonencode({ "title": "Auto Scaling EC2 instance launch failed", "description": "CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.", "source": "EC2 Auto Scaling", "category": "Availability", "severity":"2", "resources": <resources>, "operationalData": { "/aws/dedup": {"type": "SearchableString", "value": "{\"dedupString\":\"SSMOpsItems-Autoscaling-instance-launch-failure\"}"}, "/aws/automations": { "value": "[ { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGEnterStandby\" }, { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGExitStandby\" } ]" }, "autoscaling-group-name": {"value": <autoscaling-group-name>}, "status-message": {"value": <status-message>}, "start-time": {"value": <start-time>}, "end-time": {"value": <end-time>}, "cause": {"value": <cause>}} })

Expected the start of an expression, but found an invalid expression token.

**Comment by awsandy** [comment] 2023-03-05 09:30
Could you post the whole terraform file, that error on line 22 can be a result of some of the lines that preceded it

**Comment by awsandy** [comment] 2023-03-06 08:11
Please also post the full contents of the file:

aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf

This might help me reproduce the issue as I'm struggling to do so.

**Comment by ahkai86** [comment] 2023-03-06 11:20
content of aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf

> # File generated by aws2tf see https://github.com/aws-samples/aws2tf
> # aws_cloudwatch_event_target.default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget:
> resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget" {
>     arn            = "arn:aws:ssm:ap-southeast-1:530750958497:opsitem"
>     event_bus_name = "default"
> lifecycle {
>    ignore_changes = [input_transformer[0].input_template]
> }
> role_arn = aws_iam_role.OpsItem-CWE-Role.arn
>     rule           = "SSMOpsItems-Autoscaling-instance-launch-failure"
>     target_id      = "SSMOpsItems-Autoscaling-instance-launch-failureTarget"
> 
>     input_transformer {
>         input_paths    = {
>             "autoscaling-group-name" = "$.detail.AutoScalingGroupName"
>             "cause"                  = "$.detail.Cause"
>             "end-time"               = "$.detail.EndTime"
>             "resources"              = "$.resources"
>             "start-time"             = "$.detail.StartTime"
>             "status-message"         = "$.detail.StatusMessage"
>         }
> input_template = jsonencode({ "title": "Auto Scaling EC2 instance launch failed", "description": "CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.", "source": "EC2 Auto Scaling", "category": "Availability", "severity":"2", "resources": <resources>, "operationalData": { "/aws/dedup": {"type": "SearchableString", "value": "{\"dedupString\":\"SSMOpsItems-Autoscaling-instance-launch-failure\"}"}, "/aws/automations": { "value": "[ { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGEnterStandby\" }, { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGExitStandby\" } ]" }, "autoscaling-group-name": {"value": <autoscaling-group-name>}, "status-message": {"value": <status-message>}, "start-time": {"value": <start-time>}, "end-time": {"value": <end-time>}, "cause": {"value": <cause>}} })
>     }
> }

**Comment by awsandy** [comment] 2023-03-07 09:19
I don't trust the VSCode plugin - I think it gives false negatives

Does the above pass "terraform validate" ?  

If it doesn't please post the error form Terraform (not the plugin) - and the contents of 

aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf

once again.

**Comment by ahkai86** [comment] 2023-03-08 07:35
i have the output exported to a log file 
it did end with with "terraform validate" eventually.

how do i check if it pass the terraform validate for "aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf"?

<img width="896" alt="Screenshot 2023-03-08 at 3 34 11 PM" src="https://user-images.githubusercontent.com/38812404/223650139-75ef5355-469b-4067-838e-6ff4788c56b0.png">

**Comment by awsandy** [comment] 2023-03-08 13:32
If the FINAL terraform validate was ok - then all is good

If you use the "-c yes" option , or if you are using tee with every run to your own log fiel - then the errors from previous runs are still there in the log file - so I'm

**Comment by ahkai86** [comment] 2023-03-09 16:59
After terraform validate, there isnt any success text like you mentioned in your usage guide.

found new errors still pertaining to "aws_cloudwatch_event_target"

`Error: Missing argument separator

  on aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf line 22, in resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget":
  22: input_template = jsonencode("{ title": "Auto Scaling EC2 instance launch failed", "description": "CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.", "source": "EC2 Auto Scaling", "category": "Availability", "severity":"2", "resources": <resources>, "operationalData": { "/aws/dedup": {"type": "SearchableString", "value": "{\"dedupString\":\"SSMOpsItems-Autoscaling-instance-launch-failure\"}"}, "/aws/automations": { "value": "[ { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGEnterStandby\" }, { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-ASGExitStandby\" } ]" }, "autoscaling-group-name": {"value": <autoscaling-group-name>}, "status-message": {"value": <status-message>}, "start-time": {"value": <start-time>}, "end-time": {"value": <end-time>}, "cause": {"value: <cause>}} }")

A comma is required to separate each function argument from the next.`

**Comment by awsandy** [comment] 2023-03-09 17:28
ok - so next I think I'm going to have to get hold of the actual file itself - because I suspect something is being lost as things are being pasted here.

Are you able to setup a private github repo - put the file on aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf   in there 

and then allow access to my github handle "awsandy" 

Also which Terraform plugin / version  are you using with VSCode please  ?

**Comment by ahkai86** [comment] 2023-03-12 16:39
Hi @awsandy, have setup a private repo and allow you to access! 
Please kindly check if you can access it, thanks so much!

**Comment by awsandy** [comment] 2023-03-12 17:23
Yes - all good, have the files - Thank you

**Comment by awsandy** [comment] 2023-03-12 18:47
committed another attempt to fix it

**Comment by awsandy** [comment] 2023-03-15 15:55
So that's the VS-Code plug in (whose plug-in - version is it ?) you have shown

But -  does terraform validate give an error ?

**Comment by ahkai86** [comment] 2023-03-16 07:46
`user1 tf.xxxxxxxxxxxx_ap-southeast-1 % terraform validate -json
{
  "format_version": "1.0",
  "valid": false,
  "error_count": 5,
  "warning_count": 0,
  "diagnostics": [
    {
      "severity": "error",
      "summary": "Invalid character",
      "detail": "This character is not used within the language.",
      "range": {
        "filename": "aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf",
        "start": {
          "line": 22,
          "column": 442,
          "byte": 1600
        },
        "end": {
          "line": 22,
          "column": 443,
          "byte": 1601
        }
      },
      "snippet": {
        "context": "resource \"aws_cloudwatch_event_target\" \"default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget\"",
        "code": "input_template = jsonencode(\"{ \"title\": \"Auto Scaling EC2 instance launch failed\", \"description\": \"CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.\", \"source\": \"EC2 Auto Scaling\", \"category\": \"Availability\", \"severity\":\"2\", \"resources\": \u003cresources\u003e, \"operationalData\": { \"/aws/dedup\": {\"type\": \"SearchableString\",                \"value\": \"{\\\"dedupString\\\":\\\"SSMOpsItems-Autoscaling-instance-launch-failure\\\"}\"}, \"/aws/automations\": { \"value\": \"[ { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGEnterStandby\\\" }, { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGExitStandby\\\" } ]\" }, \"autoscaling-group-name\": {\"value\": \u003cautoscaling-group-name\u003e}, \"status-message\": {\"value\": \u003cstatus-message\u003e}, \"start-time\": {\"value\": \u003cstart-time\u003e}, \"end-time\": {\"value\": \u003cend-time\u003e}, \"cause\": {\"value\": \u003ccause\u003e}} }\")",
        "start_line": 22,
        "highlight_start_offset": 441,
        "highlight_end_offset": 442,
        "values": []
      }
    },
    {
      "severity": "error",
      "summary": "Invalid multi-line string",
      "detail": "Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \\n escape to represent a newline character or use the \"heredoc\" multi-line template syntax.",
      "range": {
        "filename": "aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf",
        "start": {
          "line": 22,
          "column": 950,
          "byte": 2108
        },
        "end": {
          "line": 23,
          "column": 1,
          "byte": 2109
        }
      },
      "snippet": {
        "context": "resource \"aws_cloudwatch_event_target\" \"default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget\"",
        "code": "input_template = jsonencode(\"{ \"title\": \"Auto Scaling EC2 instance launch failed\", \"description\": \"CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.\", \"source\": \"EC2 Auto Scaling\", \"category\": \"Availability\", \"severity\":\"2\", \"resources\": \u003cresources\u003e, \"operationalData\": { \"/aws/dedup\": {\"type\": \"SearchableString\",                \"value\": \"{\\\"dedupString\\\":\\\"SSMOpsItems-Autoscaling-instance-launch-failure\\\"}\"}, \"/aws/automations\": { \"value\": \"[ { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGEnterStandby\\\" }, { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGExitStandby\\\" } ]\" }, \"autoscaling-group-name\": {\"value\": \u003cautoscaling-group-name\u003e}, \"status-message\": {\"value\": \u003cstatus-message\u003e}, \"start-time\": {\"value\": \u003cstart-time\u003e}, \"end-time\": {\"value\": \u003cend-time\u003e}, \"cause\": {\"value\": \u003ccause\u003e}} }\")\n    }",
        "start_line": 22,
        "highlight_start_offset": 949,
        "highlight_end_offset": 950,
        "values": []
      }
    },
    {
      "severity": "error",
      "summary": "Invalid multi-line string",
      "detail": "Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \\n escape to represent a newline character or use the \"heredoc\" multi-line template syntax.",
      "range": {
        "filename": "aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf",
        "start": {
          "line": 23,
          "column": 6,
          "byte": 2114
        },
        "end": {
          "line": 24,
          "column": 1,
          "byte": 2115
        }
      },
      "snippet": {
        "context": "resource \"aws_cloudwatch_event_target\" \"default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget\"",
        "code": "    }\n}",
        "start_line": 23,
        "highlight_start_offset": 5,
        "highlight_end_offset": 6,
        "values": []
      }
    },
    {
      "severity": "error",
      "summary": "Invalid multi-line string",
      "detail": "Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \\n escape to represent a newline character or use the \"heredoc\" multi-line template syntax.",
      "range": {
        "filename": "aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf",
        "start": {
          "line": 24,
          "column": 2,
          "byte": 2116
        },
        "end": {
          "line": 25,
          "column": 1,
          "byte": 2117
        }
      },
      "snippet": {
        "context": "resource \"aws_cloudwatch_event_target\" \"default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget\"",
        "code": "}",
        "start_line": 24,
        "highlight_start_offset": 1,
        "highlight_end_offset": 1,
        "values": []
      }
    },
    {
      "severity": "error",
      "summary": "Missing argument separator",
      "detail": "A comma is required to separate each function argument from the next.",
      "range": {
        "filename": "aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf",
        "start": {
          "line": 22,
          "column": 33,
          "byte": 1191
        },
        "end": {
          "line": 22,
          "column": 38,
          "byte": 1196
        }
      },
      "snippet": {
        "context": "resource \"aws_cloudwatch_event_target\" \"default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget\"",
        "code": "input_template = jsonencode(\"{ \"title\": \"Auto Scaling EC2 instance launch failed\", \"description\": \"CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.\", \"source\": \"EC2 Auto Scaling\", \"category\": \"Availability\", \"severity\":\"2\", \"resources\": \u003cresources\u003e, \"operationalData\": { \"/aws/dedup\": {\"type\": \"SearchableString\",                \"value\": \"{\\\"dedupString\\\":\\\"SSMOpsItems-Autoscaling-instance-launch-failure\\\"}\"}, \"/aws/automations\": { \"value\": \"[ { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGEnterStandby\\\" }, { \\\"automationType\\\": \\\"AWS:SSM:Automation\\\", \\\"automationId\\\": \\\"AWS-ASGExitStandby\\\" } ]\" }, \"autoscaling-group-name\": {\"value\": \u003cautoscaling-group-name\u003e}, \"status-message\": {\"value\": \u003cstatus-message\u003e}, \"start-time\": {\"value\": \u003cstart-time\u003e}, \"end-time\": {\"value\": \u003cend-time\u003e}, \"cause\": {\"value\": \u003ccause\u003e}} }\")",
        "start_line": 22,
        "highlight_start_offset": 32,
        "highlight_end_offset": 37,
        "values": []
      }
    }
  ]
}`

**Comment by awsandy** [comment] 2023-03-16 09:30
Could you pop the aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf file into the private github repo for me please

**Comment by awsandy** [comment] 2023-03-16 16:48
ok - completely changed how I get the input_template that's causing all the problems here - hopefully fingers crossed this commit will nail this one

**Comment by ahkai86** [comment] 2023-03-17 10:06
Hi andy! that cloudwatch event has been fix, do let me know if i can close this issue or otherwise there is another issue for SNS topic.

<img width="1116" alt="Screenshot 2023-03-17 at 6 02 55 PM" src="https://user-images.githubusercontent.com/38812404/225874616-70b43f0e-875e-4e5c-b93c-43bcb0ea9e29.png">

<img width="865" alt="image" src="https://user-images.githubusercontent.com/38812404/225874667-7f4b7e0e-8115-49d2-8ba0-cbde7e0ac79b.png">

aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea.tf

**Comment by awsandy** [comment] 2023-03-17 11:51
Hi,

Please could you delete or rename the file aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea.tf

Then do a 

terraform state show aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1.S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea

or

terraform state show aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1.S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint

As I just need to see what the endpoint looks like in the imported state

**Comment by ahkai86** [comment] 2023-03-23 17:17
Hi @awsandy , apologies on the late reply! Was on paternity leave hence my absent on this thread.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/38812404/227284331-03c0f8c0-9e48-465a-a869-627d3c7decf7.png">

above output screenhost as executed 'terraform state show aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint"

**Comment by awsandy** [comment] 2023-03-23 21:21
Congratulations! on the new arrival, hope all went well.

Please could you delete that terraform file it's complaining about

And then do the same terraform state show  command and post the output here. Thanks

**Comment by awsandy** [comment] 2023-03-30 10:23
Sorry - command should have been:

erraform state show aws_sns_topic_subscription.arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint

**Comment by ahkai86** [comment] 2023-04-08 07:00
Hi @awsandy , apologies for the late reply again! 
I downloaded your latest code and re-run the whole scripts again

executed the following
"terraform state show aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint"
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/38812404/230708129-32787461-a480-45cf-bb4e-af58b8087bdf.png">

**Comment by awsandy** [comment] 2023-04-08 08:48
Two things look wrong here:

1. You must delete the file aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea.tf before running the terraform state show command. The error above comes from that file. The state show command shows the error in that file and doesn't show the state as a result.

2. The terraform state show command has a "__" after aws_sns_topic_subscription - it should be a "." The command should be:

terraform state show aws_sns_topic_subscription.arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint

**Comment by awsandy** [comment] 2023-04-08 08:49
Fix the two above and we shoudl that see the endpoint entry in the state file, and I'll be able to reproduce and fix the issue.

**Comment by ahkai86** [comment] 2023-04-08 14:33
> 

i did delete the tf error file previously and the result is same as the previous screenshot
![image](https://user-images.githubusercontent.com/38812404/230726895-b4951d7c-2851-46b1-8b31-9e2394d737bd.png)

**Comment by awsandy** [comment] 2023-04-08 15:55
Can you post the 
terraform state show ........ 
command you are using please

**Comment by awsandy** [comment] 2023-04-12 16:51
I'm afraid your still using the wrong command - you are using:

terraform state show aws_sns_topic_subscription__arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint

(I can see this in the image you posted)

it should be:

terraform state show aws_sns_topic_subscription.arn_aws_sns_ap-southeast-1__S3BucketActions_7a34cdd1-d6bd-4383-886b-f020112dd5ea | grep endpoint

**Comment by ahkai86** [comment] 2023-04-18 03:12
Hi @awsandy , apologies and missed out on the exact command


please see as attached screenshot again which i have executed: 
<img width="1173" alt="81419C6D-6BE7-40A8-8BB1-9D9427BEFE16" src="https://user-images.githubusercontent.com/38812404/232661376-b2cc3798-f3cd-4a30-b744-cbe304545b01.png">

**Comment by ahkai86** [comment] 2023-04-24 07:45
Hi @awsandy, yes the issue has been fixed ! It doesnt show any errors in the generated tf files anymore.

But there are some errors which shows Reference to undeclared resource, do you want me to open a new thread instead and close this? 

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/38812404/233931601-6eea58f4-fccf-4dd8-bd2d-2f7f720e3fca.png">

**Comment by awsandy** [comment] 2023-04-24 20:33
also double check those resources do actually exist in the AWS console!

**Closed** 2023-04-25 10:27 UTC
