### ISSUE TITLE
Error Missing newline after argument -> (Lambda)

### ISSUE THREAD

**Issue by ahkai86** [aws-samples/aws2tf#31] opened 2023-02-24 05:26 UTC
Hi hello! Encountered lots of lambda "Error Missing newline after argument" issues executing  "./aws2tf.sh -v yes"

> Error: Missing newline after argument
> 
> on /Users/kj/Desktop/aws2tf-master/generated/tf.xxxxxxxxxxxx_ap-southeast-1/aws_lambda_function__Delete-Expired-Tagged-Snapshot.tf line 7, in resource "aws_lambda_function" "Delete-Expired-Tagged-Snapshot":
> 7:     description                    = "This function looks at *all* snapshots that have a "DeleteOn" tag containing the current day formatted as YYYY-MM-DD. This function should be run at least daily."
> 
> An argument definition must end with a newline.
> Terraform validate ...
> 
> Error: Missing newline after argument
> 
>   on aws_lambda_function__Delete-Expired-Tagged-Snapshot.tf line 7, in resource "aws_lambda_function" "Delete-Expired-Tagged-Snapshot":
>    7:     description                    = "This function looks at *all* snapshots that have a "DeleteOn" tag containing the current day formatted as YYYY-MM-DD. This function should be run at least daily."
> 
> An argument definition must end with a newline.

**Comment by awsandy** [comment] 2023-02-24 12:41
it's because there's a quote " in the description text - it needs to be escaped.  I'll look to reproduce and post a fix shortly.

**Comment by awsandy** [comment] 2023-02-24 15:25
committed fix for this

**Comment by ahkai86** [comment] 2023-02-26 14:18
Thanks @awsandy!!  but the lambda issues still persist

` Error: Invalid resource name
│ 
│   on aws_lambda_permission.0c6fb271-192b-4a5d-9c66-ee3dbbd6f0dc.tf line 1, in resource "aws_lambda_permission" "0c6fb271-192b-4a5d-9c66-ee3dbbd6f0dc":
│    1: resource "aws_lambda_permission" "0c6fb271-192b-4a5d-9c66-ee3dbbd6f0dc" {}
│ 
│ A name must start with a letter or underscore and may contain only letters,
│ digits, underscores, and dashes.`

**Comment by awsandy** [comment] 2023-02-26 16:32
fix committed for the above aws_lambda_permission issue

**Comment by ahkai86** [comment] 2023-02-28 12:30
> Error: Missing newline after argument

  on aws_cloudwatch_event_target__default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget.tf line 22, in resource "aws_cloudwatch_event_target" "default__SSMOpsItems-Autoscaling-instance-launch-failure__SSMOpsItems-Autoscaling-instance-launch-failureTarget":
  22: input_template = "={ \"title\": \"Auto Scaling EC2 instance launch failed\", \"description\": \"CloudWatch Event Rule SSMOpsItems-Autoscaling-instance-launch-failure was triggered. Your EC2 instance launch has failed. See below for more details.\", \"source\": \"EC2 Auto Scaling\", \"category\": \"Availability\", \"severity\":\"2\", \"resources\": <resources>, \"operationalData\": { \"/aws/dedup\": {\"type\": \"SearchableString\", \"value\": \"{\\"dedupString\\":\\"SSMOpsItems-Autoscaling-instance-launch-failure\\"}\"}, \"/aws/automations\": { \"value\": \"[ { \\"automationType\\": \\"AWS:SSM:Automation\\", \\"automationId\\": \\"AWS-ASGEnterStandby\\" }, { \\"automationType\\": \\"AWS:SSM:Automation\\", \\"automationId\\": \\"AWS-ASGExitStandby\\" } ]\" }, \"autoscaling-group-name\": {\"value\": <autoscaling-group-name>}, \"status-message\": {\"value\": <status-message>}, \"start-time\": {\"value\": <start-time>}, \"end-time\": {\"value\": <end-time>}, \"cause\": {\"value\": <cause>}} }"

An argument definition must end with a newline.

**Closed** 2023-03-01 08:57 UTC
