### ISSUE TITLE
loads of errors when permission to view org is missing

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#51] opened 2023-06-12 13:17 UTC
there are loads of errors when i do not have permissions to view the org info
```bash
225-get-cvpn-endpoints.sh runtime 6 seconds
-------------------------------------------------------------------
. ../../scripts/227-get-vpn-connections.sh
Found Error: │ Error: listing AWS Organization (<redacted>) accounts: AccessDeniedException: You don't have permissions to access this resource. .... (pass for now)
import.log adjust
--> Validate Fixer
Success! The configuration is valid.
```

**Comment by awsandy** [comment] 2023-06-12 16:04
committed change that should hopefully skip around these when you don't have access

**Comment by awsandy** [comment] 2023-06-12 19:57
what was the corresponding aws2tf.sh  command you used  ?
when you saw the  skipping 030-get-iam-users.sh 
etc commands 

skipping iam stuff can be by design - because when other resources are found the necessary iam is pulled in as a dependency

If you still want ALL the iam stuff you can always do a subsequent:
./aws2tf.sh -t iam -c yes -f yes

(committed another change to get more output on the skipping - as there's two reasons that can happen)

**Comment by awsandy** [comment] 2023-06-12 20:23
committed more changes to help track this down - also please run with debug on:

./aws2tf.sh -v yes -d yes

This will help me track down the "Found Error: │ Error: listing AWS Organization (o-4oizb4q5g1) accounts:"

as it will exit soon after the error occurs (-d yes)

**Comment by marafa-sugarcrm** [comment] 2023-06-12 20:45
cmd: `./aws2tf.sh -d -v yes`

```bash
t= pre=* i= exclude=iam
loop through providers
. ../../scripts/type-get-transitgw.sh
aws --profile profile --region region --output json ec2 describe-transit-gateways --transit-gateway-ids yes --filters "Name=state,Values=available"
aws --profile profile --region region --output json  ec2 describe-transit-gateways --transit-gateway-ids yes --filters "Name=state,Values=available" : You don't have access for this resource
Success! The configuration is valid.

type-get-transitgw.sh runtime 11 seconds
-------------------------------------------------------------------
. ../../scripts/010-get-organization.sh
aws --profile profile --region region --output json organizations describe-organization
aws_organizations_organization o-??? import
╷
│ Error: listing AWS Organization (o-???) accounts: AccessDeniedException: You don't have permissions to access this resource.
│
│
╵

aws_organizations_organization.o-???: Importing from ID "o-???"...
No state file was found!

State management commands require a state file. Run this command
in a directory where Terraform has been run or use the -state flag
to point the command to a specific state location.
Found Error: │ Error: listing AWS Organization (o-???) accounts: AccessDeniedException: You don't have permissions to access this resource.
debug flag is on so exiting ....
```

**Comment by awsandy** [comment] 2024-08-22 20:31
Handled a lot better in python version , so closing, reopen if still an issue

**Closed by awsandy** 2024-08-22 20:31 UTC
